import './globals.css'
import { Lato } from 'next/font/google'

const lato = Lato({ subsets: ['latin'], weight: '400', variable: '--font-lato' })

export const metadata = {
  title: 'Weather App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${lato.variable} font-lato bg-violet bg-main`}>
        <main className='h-screen w-screen flex items-center justify-center'>
          {children}
        </main>
      </body>
    </html>
  )
}
